# Generated by Django 3.2.5 on 2021-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_realaddress', models.CharField(max_length=100)),
                ('Address_safeaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
