# Generated by Django 3.2.5 on 2021-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_address_address_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_rider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
