# Generated by Django 3.2.5 on 2021-08-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_address_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_createtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Address_storename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Address_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
