# Generated by Django 3.2.5 on 2021-08-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210824_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_usedtime',
            field=models.DateTimeField(null=True),
        ),
    ]
