# Generated by Django 3.2.5 on 2021-08-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_address_address_usedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address_usedtime',
            new_name='Address_finishtime',
        ),
    ]
