# Generated by Django 3.2.5 on 2021-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
