# Generated by Django 3.2.5 on 2021-08-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(default='settings.MEDIA_ROOT/photos/default_image.png', upload_to='images/'),
        ),
    ]
