# Generated by Django 3.2.6 on 2021-08-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Address_secretphonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Address_userwantcomment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
