# Generated by Django 3.2.6 on 2021-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210826_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_storeaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
