# Generated by Django 3.2.6 on 2021-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_user_storeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_storeaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
