# Generated by Django 3.2.6 on 2021-08-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_address_address_storeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_salt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
