# Generated by Django 3.2.6 on 2021-08-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210826_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_storeid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
